KouroshKSH/cs308-project

frontend/src/App.js, frontend/src/ContactPage.css, frontend/src/ContactPage.js, frontend/src/LandingPage.css, frontend/src/LandingPage.js, frontend/src/components/DrawerMenu.js
Our left drawer is now functional, regarding #54 .
@ArifSari-maker If all checks out, feel free to merge it or approve for merging.
1. It now has clickable items, unlike before.
2. It redirects the user if the click:
a. "Home" to landing page 
b. "About" to our project's GitHub page
c. "Contact" to a contact page
3. It collapses automatically
4. It can be used on any page since it's a component now, as `frontend/src/components/DrawerMenu.js`
5. We can later change its behavior and have the updates reflected on any page that uses it
Opens a new tab and redirects the user to our [project's page](https://github.com/KouroshKSH/cs308-project). The logic behind is:
```js
<ListItem
button
sx={{ cursor: "pointer" }}
onClick={() => {
// I chose our project's GitHub link as the "About" page
// …
```
=> Left Drawer Fix with About and Contact Page

backend/src/database/insert_bulk_users.sql
1. Check issue #72  , [link](https://github.com/KouroshKSH/cs308-project/issues/72)
2. @zeynepyaman  provided the updated code for the sake of uniformity
3. By running the new bulk insertion for users, all team members will have the same initial users
4. Note that probably no one can use the current users to log in because of the encryption (hashed passwords)
5. Only I can benefit from users 1 to 15 as I created them during user authentication
6. The rest are inaccessible for me too since I can't guess what the unhashed passwords are
Either do `npm run bulk-insert` in your backend. Or, go to MySQL and type:
```sql
SOURCE /path_to_your_project/cs308-project/backend/src/database/insert_bulk_users.sql;
```
And update the `users` table manually. 
If you don't do this, you'll probably face …
=> Updated the bulk insertion for users table

backend/src/commentManagement_cli.js, backend/src/models/reviews.js
Cli for comment management. Options for viewing all comments, and viewing based on their 'comment_approval' status. With option 3, after all the pending comments are listed, the user/product manager is asked to input review_id of an input then they are able to approve or reject the comment by inputing 1 or 2 respectively.
=> Cli for comment approval management

backend/src/controllers/orderController.js, backend/src/database/stock_status.sql
**variation_stock_view**
Added variation_id as a column. Current format looks like:
**updating stock after purchase**
Updated createOrder function to decrease stock for each purchased item. 
(to create a new order) POST http://localhost:5001/api/orders 
JWT Bearer Token with Body as:
```
{
"delivery_address": "Address 123",
"total_price": 624.94,
"items": [
{
"product_id": 1,
"variation_id": 2,
"quantity": 5,
"price_at_purchase": 19.99
},
{
"product_id": 4,
"variation_id": 17,
"quantity": 8,
"price_at_purchase": 60.00
},
{
"product_id": 7,
"variation_id": 31,
"quantity": 1,
"price_at_purchase": 44.99
}
]
}
```
Stock view before new order is created (purchased items are indicated):
Stock view after the order is created:
=> Updating stock after purchase

frontend/src/LandingPage.js
Previously, a user could add products to their cart right from the landing page. After some discussion (refer to #80 and #92 ), I decided to remove the ability to add something to cart right from the landing page. The user must go to the specific product page for what they want, choose the variation (like size), and then they'll be able to add something to their cart.
The reasoning is simple, and this PR was made to avoid having too many changes in one PR. The rest will be about changing the `carts` table structure, then another one for changing the endpoints, and one last PR for the cart page itself (refer to #73 ).
=> Removed the add to cart for each product on landing page

frontend/src/ProductPage.js
updated handleReviewSubmit function from the ProductPage.js
Now users are able to just give a rating, just comment or make comment with a rating from the product's page. Reviews are shown on the product's page once (and if) they got approved.
just comment no rating
just rating no comment
rating and comment
=> Backend connection for posting ratings and comments from product page

frontend/src/ProductPage.js
Addressed the bug #136 
All products now get their correct number of stars based on this function that reads the `popularity_score` from `products` table.
```js
const getStarsForPopularity = (score) => {
if (score <= 4) return 1;
if (score <= 5) return 2;
if (score <= 6) return 3;
if (score <= 7) return 4;
return 5;
};
```
> Of course, we can later change the numbers.
First on landing page, I wish to choose "Denim Shorts":
Then it correctly shows 2 stars now:
=> fixed issue with all products having 4 stars

frontend/src/Header.js, frontend/src/LandingPage.js, frontend/src/ProductPage.js
In reference to #130 
Code does:
1. Use `navigateToDepartment` prop to navigate (all of our pages should use this from now on)
2. Center the department names properly (got rid of `flexGrow`)
3. Some minor UI changes
I'm on landing page:
I go to the "Cargo Pants" product page:
And I click on "Kids" department:
And I end up in "Kids" department landing page:
=> Fixes for Product Page Navigation and UI

frontend/src/ProductPage.js
Refer to #139 
Basically fixed the quantity box acting weird.
Go to product.
You can choose a size and by default it assigns 1 to the quantity count.
You can now delete that number if you don't want 1, but perhaps 5 or some other single digit number (that doesn't start with 1):
And it throws errors if you leave it empty:
Also, you can't enter zero or negative numbers (by typing dash) because it automatically rejects those inputs and resets the field, which is pretty nice.
=> Fix for Product Page's Add to Cart Weird Behavior

backend/src/database/carts_schema.sql
This PR addresses the bug #157 .
I change the code in `backend/src/models/cart.js`. The modified line is:
```sql
UNIQUE KEY unique_cart_item (user_id, session_id, product_id, variation_id), -- included variation ID to avoid bug 157
```
Note that you have to drop the current `carts` table from MySQL and do a new table creation for it to make the changes work.
```sql
mysql> DROP TABLE IF EXISTS carts;
mysql> SOURCE /path_to_your_project/cs308-project/backend/src/database/carts_schema.sql;
```
cc. @zeynepyaman , @ArifSari-maker 
Go to landing page and then choose a product that has multiple variations in stock (like "Sporty Sandals").
Let's choose a singular item of Sporty Sandals with size **25-27**.
And let's choose 2 items of the same product but with variation of size **28-30**. 
> I …
=> PR for Cart Table's Schema Update about Unique Keys

backend/src/models/cart.js, frontend/src/components/MiniCart.js
This is about #159 and also more quality of life changes for the mini cart.
cc. @ArifSari-maker , @zeynepyaman 
1. The mini cart now has a uniform size.
2. If the content of the mini cart go over a threshold, it'll become scroll-able, instead of infinitely long.
3. The icons are changed from emojis to Material UI's standard icons as:
```js
import RemoveIcon from "@mui/icons-material/Remove";
import AddIcon from "@mui/icons-material/Add";
import DeleteIcon from "@mui/icons-material/Delete";
```
4. The cart items now show the size variation of the product too.
5. We can also print the color but I commented it out as below in `frontend/src/components/MiniCart.js`:
```js
<Box sx={{ flex: 1 }}>
<Typography variant="body1" fontWeight="bold">
{item.name}
</Typography>
{/* we can also show the …
```
=> PR for Mini Cart Visual Improvements

backend/src/models/reviews.js, frontend/src/ProductPage.js
Ratings not showing directly when a review is submitted is fixed. Now, getReviewsByProductId gets all reviews and we are doing the review approval status filtering directly on ProductPage.js.
Submitting review:
Immediately after submission (As you can see, the rating is posted on the productpage)
Then the comment is approved:
And after refreshing the product page it can be seen that both the rating and the comment is displayed:
Submitting a rating only review:
After reloading the page after submission: 
Submitting the review:
After reloading the page after submission. There is no reviews shown for the user:
Approving the review:
After reviews is approved it's shown in the product page:
=> Ratings not showing directly when a review is submitted is fixed

backend/src/models/cart.js, frontend/src/ProfilePage.js
In reference to #161 
This PR is about adding the feature of showing cart information on the user's profile page. Some other UI updates have happened as well.
1. We now have a "Cart" section on the profile page. 
2. It shows the products that the user has added to their cart previously. 
3. The items show general info, _and_ also include a thumbnail picture of the product.
4. The cart and orders sections are **collapse-able**.
5. I had to update the backend for `models/cart.js` a bit to make the image feature work. Just a simple inclusion of `image_url`.
6. And there's also a "Check Out" button once the user looks to the right of the price total.
7. I also added 2 Material UI icons for the sake of UI/UX improvements.
=> Updated Profile Page with Cart Items and UI Updates

frontend/src/pages/LandingPage.css, frontend/src/pages/LandingPage.js
This PR refers to #183 and is the frontend code for filtering products based on their chosen category for the current department the user is visiting.
cc. @NurAycaIlhan , @zeynepyaman , @ArifSari-maker 
After the fix for backend of the `products` table, we now can filter products based on categories of:
1. Tops
2. Bottoms
3. Shoes
4. Accessories
I used the [Material Icons](https://mui.com/material-ui/material-icons/) website to find the appropriate icons and chose them accordingly. **NOTE** that there were no clothing-specific icons, hence me choosing the ones we have. Please don't try to change these as it'll cause errors (trust me, I dealt with it).
cc. @ArifSari-maker 
This part is the important bit of code that does the mapping correctly, which should **NOT** change:
```js
const …
```
=> Filtering by Category Frontend

frontend/src/pages/ProductPage.js
First problem, "Non-informative Error Message when User Posts Reviews for the Same Products" is handled. Now if the user tries to review a product they've already reviewed they will get the "You’ve already reviewed this product." error message. It can be seen in this screenshot (I tried as ratingsreviewstestperson my previous review is at the top)
Additionally, if the user tries to review random products that they haven't purchased or the products that they purchased but haven't delivered yet, they'll get the "You can only review products you’ve purchased and received." error message.
I'm currently working on the other part of this issue: updating reviews.
=> Reviews update: updating error messages and updating posted reviews (Issue #169)

frontend/src/App.js, frontend/src/components/MiniCart.js, frontend/src/components/ProtectedRoute.js
In reference to #187 .
This code fixes the issue about not being able to go from cart to checkout (either mini cart on landing page and/or cart tab on profile page), even if the user is already logged in.
cc. @zeynepyaman 
Basically, the issue was that after writing the code for manager authentication, PR #186 , I changed the logic for navigation that would look at protected pages, and would check their `role` parameter. Now, the files `App.js`, `Minicart.js` and `ProtectedRoute.js` properly handle everything.
To double check, let's start the project and begin the test from a state of having no authentication (being logged out).
Let's log in and add some stuff to our cart. I chose the user with email address `newuser1@example.com` with the password `password1234` (this user was manually …
=> Fix for the Checkout Forgetting User Auth - Bug 187

backend/src/controllers/orderController.js, backend/src/models/deliveries.js, frontend/src/pages/ProductManagerPage.css, frontend/src/pages/ProductManagerPage.js
This PR is about #189 and #190 .
cc. @NurAycaIlhan , @zeynepyaman 
The visuals of the product manager page before this PR (everything is static besides the drawer menu and the log out button):
The very first page they see, the "Product & Category Management" section:
> It is not connected to backend yet.
The "Delivery Management" section (with a scroll-able window):
The "Comment Moderation" section:
> It is not connected to backend yet.
The filter that offers 4 options for the `deliveries` table, which shows "All" by default:
Only "Pending":
Only "Shipped":
Only "Delivered":
As you can see, if the delivery status progresses, the buttons the product manager can click get disabled.
Let's go with this example, where I already know:
```sql
SELECT
d.delivery_id,
d.order_id,
o.user_id, …
```
=> Product Manager and the Deliveries Fullstack 

frontend/src/pages/SalesManagerPage.js
I forgot to push this with #193 so just making a quick PR for merging it. Basically the sales manager page looks like this:
=> Minor UI changes for sales manager page

backend/src/models/wishlist.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/pages/LandingPage.css, frontend/src/pages/LandingPage.js, frontend/src/pages/ProductPage.css, frontend/src/pages/ProductPage.js, frontend/src/pages/ProfilePage.js
In reference to #173 
This PR is about adding wishlist functionality:
1. A wishlist button to product page (under "Add to Cart")
2. A wishlist _clickable_ icon to product card on landing page (per product)
3. A wishlist tab on customer's profile page (next to "Orders, Cart")
4. Doing proper checks before adding to wishlist (authenticated user).
---
If the person isn't logged in, the product page will have a disabled wishlist button, so that they wouldn't be able to click.
Even if they choose a variation, it doesn't make a difference of course:
> I'm currently not logged in.
For the sake of this demo, let's check what the current `wishlists` table looks like:
```sql
select * from wishlists;
```
Which gives:
```
+-------------+---------+------------+--------------+---------------------+
| …
```
=> Frontend for Wishlist

frontend/src/pages/ManagerLogin.js
This PR resolves the hydration error on the manager authentication page—“In HTML, <div> cannot be a descendant of <p>”—by adjusting how we render secondary text in MUI’s ListItemText. MUI’s default behavior wraps secondary content in a <p>, so passing JSX containing <div>s directly causes invalid nesting and a React hydration mismatch.
What Changed:
ListItemText
Added secondaryTypographyProps={{ component: 'div' }} so that the secondary block is rendered as a <div> instead of a <p>.
Wrapped all secondary content in plain <div>s (no change to actual content), which now live inside that parent <div> rather than a <p>.
Why This Fixes #197
By telling MUI to render secondary text as a <div>, we eliminate the invalid <div>-inside-<p> structure. This restores valid HTML, removes the hydration …
=> [BUG] Fix hydration error (#197)

backend/src/controllers/returnsController.js, backend/src/database/returns_schema.sql, backend/src/models/productVariations.js, backend/src/models/returns.js, frontend/src/pages/OrderStatusPage.js, frontend/src/pages/ProductPage.js, frontend/src/pages/SalesManagerPage.js
Mainly in reference to #228 but with many other stuff.
cc. @zeynepyaman 
```sql
DROP TABLE IF EXISTS returns;
```
```sql
CREATE TABLE IF NOT EXISTS returns (
return_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
order_id BIGINT UNSIGNED NOT NULL,
user_id INT,
refund_amount DECIMAL(10,2),
status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (order_id) REFERENCES orders(order_id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL
);
```
And remake it via:
```sql
SOURCE /.../cs308-project/backend/src/database/returns_schema.sql
```
Make sure you have it now:
```sql
select * from returns;
```
So as an example, I knew I had this order from an account:
And therefore, I decided to insert …
=> Sales Manager Handling Returns (frontend, backend, database)

backend/src/controllers/orderController.js, backend/src/routes/orderRoutes.js, frontend/src/pages/OrderStatusPage.js
Order cancellation full stack
Only allows if status is processing, returns back stock after successful cancellation.
PATCH http://localhost:5001/api/orders/33/cancel
```
curl -X PATCH http://localhost:5001/api/orders/33/cancel \
-H "Authorization: Bearer YOUR_JWT_TOKEN"
```
Can't cancel 34 because it's in-transit:
Before cancellation stock:
After cancellation stock:
NOTE: There is also new icons for order statuses. 
Doesn't allow cancellation if status is not processing.
Before cancelling order items stock:
When clicked cancel order button this pops up :
If yes is selected, order is successfully cancelled (nothing happens if you select no):
Stock after cancellation:
=> Order cancellation

backend/src/controllers/orderController.js, backend/src/controllers/returnsController.js, frontend/src/pages/OrderStatusPage.js
POST http://localhost:5001/api/returns
{
"order_id": 43
}
```
curl -X POST http://localhost:5001/api/returns \
-H "Authorization: Bearer YOUR_JWT_TOKEN_HERE" \
-H "Content-Type: application/json" \
-d '{"order_id": 43}'
```
Doesn't allow if order status is not delivered
Doesn't allow if it's been more than 30 days since order created.
Manually update order_date:
```
UPDATE orders
SET order_date = '2025-04-01'
WHERE order_id = 42;
```
Also fixed the issue of being able to request return multiple times, now you the user can only request once per order.
Successful return request:
Doesn't allow if order status is not delivered
Doesn't allow if it's been more than 30 days since order created.
Manually updated date again:
Also fixed the issue of being able to request return multiple times, now …
=> createReturn updated + returns frontend + fix for issue #249
