- backend/src/server.js
- sets up a basic online shop (a server)
- it can receive orders (requests), process them, and send responses
- uses tools to manage secrets, handle orders in a specific format, and control who can access the shop
- also has a simple sign that says "API is running..." to let visitors know it's working
> Did the server setup

- script.sh
- Created `script.sh` in the root directory to automate the startup process.
- The script checks the current directory, verifies Node.js and npm versions.
- Starts the backend server using `npx nodemon`.
- Starts the frontend server using `npm start`.
- Provides clear messages to guide the user through the process.
> Wrote script to automate backend and frontend

- frontend/src/App.js
- frontend/src/Login.test.js
- frontend/src/signUp.js
This pull request introduces a new Sign Up page to the application and updates the routing and imports accordingly. 
Added SignUp.js with name, email, and password fields.
Linked Sign-Up to the login page (Login.js).
Updated App.js to include /signup route.
Ready for review. 🚀
> AAdded Sign-Up Page & Linked to Login

- frontend/src/App.js
- frontend/src/LandingPage.css
- frontend/src/LandingPage.js
- frontend/src/Login.js
- frontend/src/Signup.js
This pull request introduces the initial version of the Landing Page desing for our project, built using React and Material UI (MUI).
✅ Features Included:
🌐 Transparent AppBar fixed to the top of the page.
👚 Category selection for "Kadın", "Erkek", and "Çocuk" (with dynamic content update).
🍔 Left-aligned hamburger menu with a working Drawer (side menu).
🔍 Right-aligned Search, Basket, and Profile icons.
👤 Profile icon routes to the /login page.
> Final fix branch 1

- frontend/src/App.js
- frontend/src/Login.js
- frontend/src/ProtectedRoute.js
- package-lock.json
- package.json
Fix the bug with the user being able to bypass user authentication to jump directly to the `/dashboard` page.
- the user could go to dashboard without logging in
- added a protected route to the dashboard
- now the user can't go to dashboard unless they log in
- had to install 2 libraries
> Fixed Dashboard Route by Auth Bypass

- frontend/src/LandingPage.js
- bug #28 
- before this PR, the language of the website was a mix of Turkish and English.
- now everything is in English as we agreed upon.
> changed all turkish words to english

- frontend/src/Login.js
- frontend/src/Signup.js
- feature #32 
- before, user couldn't go back to landing page from user authentication screens (i.e. login, signup)
- now they can using the "back to home" button; top left corner
> added back to home button for user auth screens

- backend/src/database/testing_login.txt
- frontend/src/App.js
- frontend/src/CheckoutPage.js
- frontend/src/LandingPage.js
- frontend/src/Login.js
- frontend/src/ProfilePage.js
- frontend/src/Signup.js
This PR handled the following:
1. Adding a cart to the website
2. Being able to add products to said cart
3. Checking out from cart to the checkout page
4. A new checkout page
5. If not logged in, first authenticate user and then go to checkout page
6. If already logged in, go straight to checkout page
7. A new profile page for any authenticated user that display certain info
1. #41 
2. #43 
3. #45 
4. #46
> New Features: Cart, Checkout and Profile Page

- frontend/src/App.js
- frontend/src/Header.js
- frontend/src/Login.test.js
- frontend/src/ProductPage.css
- frontend/src/ProductPage.js
- package-lock.json
📝 Pull Request Title:
Add Product Page with Gallery, Dynamic Content, and Review Features
📄 Description:
This pull request introduces a fully functional Product Page component for the e-commerce platform.
✅ Product Information
Includes name, price, description, seller, and available sizes. All pulled dynamically based on the URL productId.
✅ Size Selection + Add to Cart
Users can select a size and add the product to their cart. Cart logic is currently local but designed to integrate with global state or backend.
✅ Dynamic Category Navigation
The page passes the product’s category dynamically to the shared Header component for accurate category highlighting.
✅ Customer Reviews (Read & Write)
Simulated fetch of reviews using useEffect and mock data
Prepared for future backend integration …
> Product Page

- frontend/src/Cart.js
Changes Made:
- Added quantity control (increase/decrease) for items in the cart.
- Implemented size selection (S, M, L) for each product.
- Included a cart icon in the header with a badge displaying the number of items in the cart.
- Improved user interaction with hover effects and responsive design for better UX.
Purpose:
These changes aim to enhance the cart page by providing more control to users over the items they add to the cart, making it easier to adjust quantities and select product sizes. The cart icon also gives users a quick overview of their shopping cart.
> Add cart page features (quantity control, size selection, and cart icon)

- backend/src/controllers/productController.js
- backend/src/database/bulk_insert.js
- backend/src/database/create_db_run_schema.sql
- backend/src/database/insert_bulk_product_reviews.sql
- backend/src/database/insert_bulk_users.sql
- backend/src/database/product_reviews_schema.sql
- backend/src/insert_user.js
- backend/src/models/index.js
- backend/src/models/reviews.js
- backend/src/routes/productRoutes.js
Completed the endpoint for getting product reviews, in regards to #65 :
1. now we can get the product reviews by product id
2. added a new model for reviews
3. added a new route for getting product reviews
Example to run in Postman:
- Method: `GET`
- URL: `http://localhost:5000/api/products/1/reviews` (replace 1 with the desired product ID)
- Header: None
- Body: None
The response will be:
```json
[
{
"review_id": 15,
"product_id": 1,
"rating": 5,
"comment": "This shirt is soft and fits great!",
"created_at": "2025-04-15T18:35:32.000Z",
"username": "john.doe_541712"
},
{
"review_id": 16,
"product_id": 1,
"rating": 4,
"comment": "Decent quality. I might buy again.",
"created_at": "2025-04-15T18:35:32.000Z",
"username": "michael_brown"
},
{
"review_id": 17,
"product_id": 1,
"rating": null, …
```
> Getting Product Review Endpoint and Database

- backend/src/server.js
- frontend/src/LandingPage.js
In reference to #79 . Now, the frontend people can use their local environmental variables to perform their requests to backend, without worrying about port number issues and/or URL changes. We should all use this new approach from now on and include the necessary info in our prompts for the LLMs.
cc. @ArifSari-maker , @NurAycaIlhan , @zeynepyaman , @reyhanturhan 
Make sure you have the following files in your project because they're in `.gitignore`, so you won't have them on your computer unless you create them manually:
1. `backend/.env`: Go to the backend folder of the project. Create a file called `.env` (dot env). 
2. `frontend/.env`: Go to the backend folder of the project. Create a file called `.env` (dot env). 
Make sure to tell the LLM that: _"I have environmental variables and I …
> Fix for Using Environmental Variables as URLs and Port Numbers

- backend/src/controllers/authController.js
- backend/src/models/user.js
- backend/src/server.js
- frontend/src/Signup.js
As mentioned in #74 , our sign up page stopped working randomly. After going through the code, I noticed the issues and addressed them. In summary:
1. It was using the wrong route. Now it uses the `.env` to always use the same URL.
2. It was passing `name` as a field, which I changed to `username` since our `users` database has a `username` column, not `name`. 
3. I also removed the unnecessary inclusions of fake address and phone number fields in the user insertion queries. 
Now you can go to the signup page via the `http://localhost:3000/signup` URL. In the following screenshots, you can see the results of the networks tab (press `f12`) of my browser. Basically same as Postman, it's just better looking.
The request was successfully posted (via `axios.post(...)`):
The body of the request …
> Fix for Signup / User Registration

- backend/src/database/insert_bulk_product_reviews.sql
- backend/src/database/product_reviews_schema.sql
The `product_review` table now has an extra column for approval of comments. This is necessary for the product page @ArifSari-maker . Refer to #90 and #76 for more info.
1. Thanks to @zeynepyaman  's advice, our product reviews table now has an extra column.
2. The `comment_approval` column is by default pending, and only the product manager can adjust its value.
3. Everyone should update their product reviews table by:
1. Delete the old table
2. Run the new Schema
3. Insert the new data
> At this point, I really hope that everyone can understand those 3 steps without me having to write the exact SQL for it.
> Updated the Product Reviews Schema and Insertion

- backend/src/controllers/productController.js
- backend/src/models/product.js
- backend/src/models/reviews.js
- backend/src/routes/productRoutes.js
- frontend/src/App.js
- frontend/src/LandingPage.js
- frontend/src/ProductPage.css
- frontend/src/ProductPage.js
- frontend/src/tempProductPage.css
- frontend/src/tempProductPage.js
Referring to #95 
This PR handles the following:
1. When on landing page, `http://localhost:3000/`, the products are clickable.
2. By clicking on a product (e.g., "Women" department, "Fitted Jacket" product), the user gets redirected to a dedicated product page (it's currently called `tempProductPage.js` to avoid changing @ArifSari-maker 's code for `ProductPage.js`).
3. On that page (e.g., `http://localhost:3000/tempProductPage/7`), the user can see the product info and also the product reviews. Note that only the "approved" product reviews will be shown. Refer to #94 for more info.
4. Once the images from @reyhanturhan are in, we can use them to show the product images too.
5. This product page also has a drawer, which is useful for not only page navigation, but also a uniform design …
> Going from Landing Page to Product Page

- backend/src/controllers/cartController.js
- backend/src/database/carts_schema.sql
- backend/src/models/cart.js
In reference to #92 
Previously, the cart backend did not allow for variations of products. With this PR, our `carts` table (there is an _S_ at the end) now can also keep track of what variation the product has, and the endpoints send the proper requests.
cc. @ArifSari-maker , @NurAycaIlhan , @zeynepyaman 
I suggest you all to read this PR because in case I can't get to finish cart, maybe someone can use the logic to fix the frontend for cart
1. First, make sure you remove the `cart` table from your DB if you have it. If you don't then it's fine. Verify this by typing `SHOW TABLES;` and looking for `cart` (without an _S_).
2. Then, create the `carts` table (with an _S_) by running:
```sql
SOURCE /your_project_path/cs308-project/backend/src/database/carts_schema.sql;
```
3. Once done, you …
> Redesign of Cart DB and Endpoints

- backend/src/controllers/authController.js
- backend/src/controllers/cartController.js
- backend/src/controllers/productController.js
- backend/src/models/cart.js
- backend/src/models/product.js
- backend/src/routes/cartRoutes.js
- backend/src/routes/productRoutes.js
- frontend/src/tempProductPage.js
- frontend/src/utils/sessionStorage.js
This PR is about generating session IDs, using either the session ID or the user ID (if authenticated), and allowing a person to add something to their cart via the product page **only** (we no longer offer add to cart via landing page). The frontend, backend, and DB are all handled.
cc. @ArifSari-maker , @NurAycaIlhan You have to read this PR. Either way, I'll handle everything, even frontend because it's too late to ask for much.
cc. @zeynepyaman Here's a typical flow of how a frontend page like `tempPorductPage.js` can `get()` and such requests to fetch data, and then `post()` the desired requests to the backend/DB. Here's the general outline: 
`frontend -> axios -> authentication [if needed] -> route -> controller -> model`
You can understand everything better by going through the …
> Adding Product to Cart from Product Page (Frontend, Backend, DB)

- backend/src/controllers/productController.js
- backend/src/models/reviews.js
- backend/src/routes/productRoutes.js
This PR is about #67 .
With thanks to the PR #101 from @zeynepyaman , this code now allows a user to post a product review via the backend and DB. For now, it's not available through UI (frontend). I'll do that too on the `tempProductPage.js` as I won't bother with `ProductPage.js` at this point.
cc. @ArifSari-maker 
1. A couple of checks are performed before the creation of a review
1. Check if the person has already reviewed this product (we might have to change this later for stuff like "Edit Review" and such)
2. Check if the person has actually purchased this product (doesn't care about variation, purely the `product_id`).
3. Check if the person has received the product (the `status = "delivered"` condition in the `orders` table).
4. And of course, the person should be authenticated …
> Backend and DB Code for Posting a Product Review

- backend/src/controllers/authController.js
- backend/src/controllers/orderController.js
- backend/src/models/cart.js
- frontend/src/Login.js
- frontend/src/utils/sessionStorage.js
The following PR is about addressing these issues:
1. #127 
2. #124 
3. #128 
4. #129 
Read the bugs for more info. I've written more than enough explanation already in the comments there.
> Major Fix for Backend and DB on Cart and Checkout Side

- backend/src/controllers/orderController.js
- backend/src/database/deliveries_schema.sql
- backend/src/database/popularityFormula.sql
- backend/src/deliveryManagement_cli.js
- backend/src/models/deliveries.js
- package-lock.json
Created a mysql event that updates every 24 hours and calculates the necessary values such as average rating, comment count per product and then inputs them to its formula. 
```
popularity_score = (IFNULL(r.avg_rating, 0) * 1.5) + 
(IFNULL(r.comment_count, 0) * 0.1) * 
EXP(-0.02 * DATEDIFF(NOW(), IFNULL(r.latest_comment_date, NOW())));
```
We are calculating how many days have passed since the date of last approved comment and apply a 0.02 exponential decay rate to it.
İnitially tried it with avg_rating * 1 and comment_count * 0.1 however due the the low number of comments each product's score was below 5. To make it more realistic (and generally positive) avg_rating is now multiplied with 1.5 which gives us 4-7 range.
when avg_rating was multiplied by 1:
current values:
> Popularity score formula

- backend/src/controllers/orderController.js
- backend/src/controllers/userController.js
- backend/src/database/deliveries_schema.sql
- backend/src/database/popularityFormula.sql
- backend/src/deliveryManagement_cli.js
- backend/src/models/deliveries.js
- backend/src/models/user.js
- backend/src/routes/index.js
- backend/src/routes/userRoutes.js
- frontend/src/ProfilePage.js
- package-lock.json
- package.json
You need to have this line in your .env file with your backend port:
`REACT_APP_API_URL=http://localhost:5001/api`
It fetches and displays user profile data username, email, phone number and address and also user's order history from backend. Orders are collapsible with the clickable orders text. There are also working back to home and log out buttons.
How it looks with newly signed up user:
> User Profile Page

- frontend/src/LandingPage.css
- frontend/src/LandingPage.js
Initially done by @NurAycaIlhan , I simply copied her code since there were some minor things I had to change. Basically the code adds star rating to products on landing page.
The thresholds are as below in `frontend/src/LandingPage.js`:
```js
const getStarsForPopularity = (score) => {
if (score <= 4) return '⭐';
if (score <= 5) return '⭐⭐';
if (score <= 6) return '⭐⭐⭐';
if (score <= 7) return '⭐⭐⭐⭐';
return '⭐⭐⭐⭐⭐';
};
```
Note that in #125 PR, @zeynepyaman wrote a script about updating the popularity scores. We can run it and change the constants. I went with these thresholds for frontend because it looked decent. We can change later of course.
> Added star ratings based on popularity score

- frontend/src/utils/sessionStorage.js
Tefer to #142 
It now refreshes every 5 minutes.
> made session ID expire every 5 min

- backend/src/controllers/orderController.js
- backend/src/controllers/orderItemController.js
- backend/src/routes/orderRoutes.js
- frontend/src/OrderStatusPage.js
- frontend/src/ProductPage.js
- frontend/src/ProfilePage.js
- package-lock.json
- package.json
Connected users profile listed on the user profile page to order status page. When you click a certain order, that order's order status page is displayed. Expected delivery is set as order date + 7.
Also added a New function added to orderController to properly fetch order items to be displayed.
examples:
> Order to order status

- frontend/src/Header.js
- frontend/src/LandingPage.js
- frontend/src/components/MiniCart.js
- frontend/src/utils/sessionStorage.js
- This PR is about #145 . The code makes a mini cart that successfully gets the data of the person's cart.
- It makes a new component called `MiniCart.js`. Can be modified easily to show what we want.
- Currently it's product name, price, quantity.
- Has a "go to cart" button that should redirect to cart page (which doesn't work now).
- After discussing it with @zeynepyaman , we decided to make it redirect to checkout page instead.
- The buttons for :heavy_plus_sign: , :heavy_minus_sign: , and :wastebasket: will take care of updating the cart items.
- It also works if someone adds stuff while anon visitor, and then log in. Their cart will be assigned to them.
First, let's make sure we're not logged in:
I won't log in and just go to landing page:
> If I was logged in, I would see my JWT in …
> PR for Mini Cart

- backend/src/controllers/authController.js
- frontend/src/App.js
- frontend/src/CheckoutPage.js
- frontend/src/InvoicePage.js
- frontend/src/Login.js
- frontend/src/Signup.js
- frontend/src/components/MiniCart.js
Did #148 and then a full demo test as #82 
Everything works. I simply don't have energy to provide screenshots here. Just join the demo and watch.
> Feature for Cart to Checkout to Invoice and Full Demo Test Success

- frontend/package-lock.json
- frontend/package.json
- frontend/src/InvoicePage.js
> invoice pdf works now thanks to Zeynep

- frontend/src/Header.js
- frontend/src/LandingPage.js
Refer to #151 
Also, search works better now because we're handling wild cards.
> Fixed Search in Header and Backend for Better Results

- frontend/src/Header.js
- frontend/src/ProfilePage.js
1. made order items look clickable on profile page
2. made header have blur
3. made sure drawer is on top of header to not get blurred accidentally
> Some Styling Touches for UI

- frontend/src/pages/ProductManagerPage.js
Add Product Manager Page
Moved and added ProductManagerPage.js under src/pages
Static UI only
Matches CLI logic and ProfilePage.js layout
No changes made to App.js as instructed
> Move and add Product Manager Page to pages directory

- backend/src/controllers/deliveriesController.js
- backend/src/controllers/reviewsController.js
- backend/src/insert_user.js
- backend/src/models/deliveries.js
- backend/src/routes/deliveriesRoutes.js
- backend/src/routes/index.js
- backend/src/routes/reviewsRoutes.js
NOTE: the user must be a product manager
POSTMAN: (With JWT Bearer Token) GET http://localhost:5001/api/deliveries/status/shipped - http://localhost:5001/api/deliveries/status/pending - http://localhost:5001/api/deliveries/status/delivered 
CURL: curl -X GET http://localhost:5001/api/deliveries/status/shipped \
-H "Authorization: Bearer <your_token>"
http://localhost:5001/api/deliveries/status/pending \
-H "Authorization: Bearer <your_token>"
http://localhost:5001/api/deliveries/status/delivered \
-H "Authorization: Bearer <your_token>"
(With JWT Bearer Token)
**getting all reviews**
GET: http://localhost:5001/api/reviews
CURL: curl -X GET http://localhost:5001/api/reviews \
-H "Authorization: Bearer <your_token>"
**getting all approved reviews**
GET: …
> Endpoints for reviews + getdeliveriesbystatus

- backend/src/controllers/deliveriesController.js
- backend/src/controllers/reviewsController.js
- backend/src/controllers/wishlistController.js
- backend/src/database/create_db_run_schema.sql
- backend/src/database/wishlist_schema.sql
- backend/src/database/wishlists_schema.sql
- backend/src/models/deliveries.js
- backend/src/models/wishlist.js
- backend/src/routes/deliveriesRoutes.js
- backend/src/routes/index.js
- backend/src/routes/reviewsRoutes.js
- backend/src/routes/wishlistRoutes.js
Has wishlist_id, user_id, product_id, variation_id and added_at columns. Added added_at column so perhaps an order by date function might be implemented on the wishlist page.
**POST http://localhost:5001/api/wishlist/add**
(with body:)
CURL:
```
curl -X POST http://localhost:5001/api/wishlist/add \
-H "Authorization: Bearer < your_token >" \
-H "Content-Type: application/json" \
-d '{"product_id": 15, "variation_id": 68}'
```
Successful addition to wishlist:
Body used: 
```
{
"product_id": 15,
"variation_id": 68
}
```
Out of stock variations can also be added to wishlist: (stock amounts can be seen in one of the screenshots below)
Body used: 
```
{
"product_id": 15,
"variation_id": 67
}
```
Variation is not necessary for wishlist addition it can be assigned null: 
Body used: 
```
{ …
```
> Schema and endpoints for wishlist

- backend/package-lock.json
- backend/package.json
- backend/src/controllers/productController.js
- backend/src/models/index.js
- backend/src/models/product.js
- backend/src/routes/productRoutes.js
- backend/src/server.js
productModel.js
→ Added getProductsByDepartmentAndCategory(departmentId, categoryId) method that performs a JOIN between products and categories tables and filters by both department and category.
productController.js
→ Added getFilteredProducts controller method to handle the new endpoint.
→ Ensures both parameters are validated and properly passed to the model method.
productRoutes.js
→ Added a new route:
GET /api/products/filter/:departmentId/:categoryId
--Tested successfully using Postman with real MySQL database data.
1: "This Postman test demonstrates a successful GET request to the /api/products/filter/:departmentId/:categoryId endpoint. It returns products that belong to both the specified department and category. In this example, department ID 2 and category ID 2 return a product …
> Add filtering products by department and category

- backend/src/controllers/authController.js
- backend/src/database/testing_login.txt
- backend/src/insert_user.js
- backend/src/routes/authRoutes.js
- frontend/src/App.js
- frontend/src/components/DrawerMenu.js
- frontend/src/components/ProtectedRoute.js
- frontend/src/pages/ManagerLogin.js
- frontend/src/pages/ProductManagerPage.js
- frontend/src/pages/ProfilePage.js
- frontend/src/pages/SalesManagerPage.js
This PR is about #185 . The files that are changed refer to the frontend and backend code responsible for logging in a manager given their chosen role (product manager and sales manager). 
You can attempt to visit the product manager and sales manager page **only** after successfully authenticating via the _manager login page_.
cc. @zeynepyaman , @reyhanturhan , @NurAycaIlhan 
In order to even try out these manager login attempts, you have make sure you at least have a product manager and a sales manager on your database in the `users` table. I have already explained that by running `backend/src/insert_user.js` with custom info, you can create a user manually (customer, product manager, and sales manager). So go to your backend terminal and type:
```
node backend/src/insert_user.js
```
As …
> Manager Authentication Page - Fullstack

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/SalesManagerPage.css
- frontend/src/pages/SalesManagerPage.js
- Added a static bar chart to SalesManagerPage using Recharts
- Displays dummy product sales data (Product 1–4)
- Will be updated to use backend endpoint once it's ready
> Add static sales bar chart to SalesManagerPage

- backend/src/controllers/authController.js
- frontend/package-lock.json
- frontend/src/components/Footer.js
- frontend/src/pages/LandingPage.js
Summary
- Added Footer component (`src/components/Footer.js`)
- Contains navigation links to Home, About, Contact, Manager
- Manager link dynamically redirects based on role from token
This PR exists due to branch protection on `feature/footer`.
> Fix: Push footer component changes via new branch

- frontend/src/App.css
- frontend/src/App.js
- frontend/src/components/Footer.css
- frontend/src/components/Footer.js
- frontend/src/pages/ContactPage.css
- frontend/src/pages/ContactPage.js
- frontend/src/pages/LandingPage.css
- frontend/src/pages/LandingPage.js
- frontend/src/pages/OrderStatusPage.css
- frontend/src/pages/OrderStatusPage.js
- frontend/src/pages/ProductManagerPage.js
- frontend/src/pages/ProductPage.css
- frontend/src/pages/ProductPage.js
- frontend/src/pages/ProfilePage.js
- frontend/src/pages/SalesManagerPage.js
In reference to #200 . I basically added to footer to almost all the pages I saw fit. For example, user authentication pages (both customer and managers) don't have it. But almost every other page has it (unless I have forgotten to).
And yes, everything is clickable in the footer and redirects correctly. If you're wondering why they're blue, it's due to a very weird issue about how different browsers handle rendering hyperlinks on websites, even normal vs. private tabs render it differently. Hence, I couldn't make the text dark gray and it's stuck as blue.
landing page:
user page (if customer):
order status page:
manager pages (both look the same):
contact us page:
> Footer for Almost All Necessary Pages

- frontend/src/pages/ProductManagerPage.js
In reference to #207 . The product manager can now view comments, filter them, and change their status (approve/reject).
What the manager initially sees:
They can filter based on status, like "Pending, Approved, Rejected":
They can also change the status, but before that, let's double check with DB:
```sql
select * from product_reviews where comment_approval = 'pending';
```
Gives us:
```
+-----------+------------+---------+--------+-----------------------+------------------+---------------------+
| review_id | product_id | user_id | rating | comment               | comment_approval | created_at          |
+-----------+------------+---------+--------+-----------------------+------------------+---------------------+
|        53 |          1 |       1 |   NULL | this product sucks!!! | …
```
> Frontend for Comment Moderation by Product Manager

- frontend/src/App.js
- frontend/src/components/DrawerMenu.js
- frontend/src/components/Footer.js
- frontend/src/pages/AboutPage.js
In reference to #201 .
A very simple "About" page that holds some basic info. Definitely needs an update.
cc. @ArifSari-maker please handle this
> Temporary About Us Page

- backend/src/controllers/authController.js
- backend/src/controllers/orderController.js
- backend/src/controllers/reviewsController.js
- backend/src/database/products_schema.sql
- backend/src/models/order.js
- backend/src/models/reviews.js
- backend/src/routes/orderRoutes.js
- backend/src/routes/reviewsRoutes.js
Added updateReview function. Reviews and rating can be both separately and together be updated. As it is for posting reviews, the ratings are immediately updated and comment part's status updates to 'pending' and needs to be approved again.
(using review id) PATCH http://localhost:5001/api/reviews/[reviewId] 
with body:
{
"rating": 5,
"comment": "updating review"
}
```
curl: curl -X PATCH http://localhost:5001/api/reviews/[reviewId] \
-H "Content-Type: application/json" \
-d '{
"rating": 5,
"comment": "updating review"
}'
```
Before updating: 
Initially, rating is updated and comment went to approval.
After comment got approved.
Another example:
Before updating: 
```
{
"rating": null,
"comment": "added coment and made rating 0"
}
```
```
{
"rating": 5,
"comment": ""
}
```
> Editing reviews -backend

- backend/src/controllers/orderController.js
- backend/src/models/cart.js
- backend/src/models/product.js
- backend/src/models/wishlist.js
- frontend/src/components/MiniCart.css
- frontend/src/components/MiniCart.js
- frontend/src/pages/CheckoutPage.css
- frontend/src/pages/CheckoutPage.js
- frontend/src/pages/ProfilePage.css
- frontend/src/pages/ProfilePage.js
In reference to #221 and #222 
cc. @ArifSari-maker , @zeynepyaman 
Now mini cart shows:
The cart tab on profile page shows
And the wishlist tab/collapsable on profile page shows (for both discounted and non-discounted products at the same time):
The sort by price now correctly shows everything (even with discount):
The sort by popularity correctly shows everything (considering discount too):
Filter by category now works (including discounts):
Search now works too (including discounts):
The checkout page now has the _Tax ID_ field (as requested by project document) and also shows discounts:
Basically creating an order with discounted prices is now fixed. To double check, let's verify our `orders` and `order_items` table for purchasing the same set of products in the last screenshot (2 out …
> Fixes for Sales Campaigns about Cart, Wishlist, Checkout, Sort, Search and Filter

- backend/src/controllers/orderController.js
- backend/src/models/reviews.js
- backend/src/routes/orderRoutes.js
- frontend/src/pages/ProductManagerPage.css
- frontend/src/pages/ProductManagerPage.js
- frontend/src/pages/ProfilePage.js
In reference to #226 and #211 
Reviews are now shown with their ID on comment moderation page:
Delivery management now has a print to PDF button:
And it actually works:
The customer can now see their order's date from the card items from their profile page too:
> Product Manager and Customer Pages Updates

- backend/src/controllers/categoryController.js
- backend/src/models/category.js
- backend/src/routes/categoryRoutes.js
- backend/src/routes/index.js
- frontend/src/pages/ProductManagerPage.css
- frontend/src/pages/ProductManagerPage.js
In reference to #242 , #244 , #245 
cc. @zeynepyaman 
---
Some new endpoints:
```
curl http://localhost:5000/api/categories
```
Gives:
```json
[
{
"category_id": 1,
"category_name": "Men",
"parent_category_id": null,
"parent_name": null
},
{
"category_id": 2,
"category_name": "Women",
"parent_category_id": null,
"parent_name": null
},
{
"category_id": 3,
"category_name": "Kids",
"parent_category_id": null,
"parent_name": null
},
{
"category_id": 4,
"category_name": "Tops",
"parent_category_id": 1,
"parent_name": "Men"
},
{/* all of them */},
{
"category_id": 63,
"category_name": "Jewellery",
"parent_category_id": 47,
"parent_name": "Accessories"
}
]
```
And also filter by department:
```
curl http://localhost:5000/api/categories/descendants/1
```
Gives:
```json
[
{
"category_id": 4, …
```
> Product Manager Category Management, Fixes for Deliveries and Comments, Separation of Product from Category Management

- frontend/src/pages/AboutPage.js
This pull request refactors the About page layout for a more polished and brand-consistent appearance.
Summary of changes:
- Centered the Noire Vogue logo at the top of the page
- Removed redundant "Noire Vogue" text to avoid visual repetition
- Cleaned up unnecessary visuals and simplified the layout
- Improved spacing, text alignment, and overall visual hierarchy
No changes were made to logic, routing, or shared components.  
Only the AboutPage.js file was modified.
> Redesign About page: centered logo, clean layout, no visual clutter

- frontend/src/pages/SalesManagerPage.css
- frontend/src/pages/SalesManagerPage.js
In reference to #250 
What sales manager sees immediately:
Hover works:
Bar chart too:
Extra chart because @zeynepyaman wrote the endpoint for it, so why let it go to waste?
Time filter works real-time without the need to even submit or press anything:
> This took me less than an hour in total. How is it possible that someone can take 6 days to make a PR that does half of this while at the same time breaking the whole sales manager page by writing code like this:
> The number of lines deleted is __Literally__ **10 TIMES MORE** than the number of added lines!!! Are you kidding me?
> Sales Manager and Charts

- frontend/src/pages/SalesManagerPage.js
Frontend for sales manager doing invoice management is done.
What he says when he opens the page:
If filtered for time:
> Actually shrinks if you filter for more recent orders.
And the download PDF works:
> Frontend for Invoice Management for Sales Manager

- backend/src/controllers/orderController.js
- backend/src/models/order.js
- backend/src/models/product.js
- frontend/src/pages/LandingPage.js
- frontend/src/pages/ProductPage.js
- frontend/src/pages/SalesManagerPage.js
In reference to #252 
What manager sees upon entry:
They can filter:
For the sake of checking "Unpriced" products, I used curl to manually insert a dummy product. My `products` table before this insertion:
```
mysql> select product_id, serial_number, name, price, cost, department_id, category_id, stock_quantity, popularity_score from products;
+------------+---------------+------------------------+-------+-------+---------------+-------------+----------------+------------------+
| product_id | serial_number | name                   | price | cost  | department_id | category_id | stock_quantity | popularity_score |
+------------+---------------+------------------------+-------+-------+---------------+-------------+----------------+------------------+
|          1 | SN10          | Cotton …
```
> Price Managmenet for Sales Manager

- frontend/src/pages/ProductManagerPage.js
Adding fields:
At least 1 variation is required:
Successfully added:
After deletion, it is removed:
Works the same way but i don't want to touch the original 15 products and we don't have time for me to add a new product and a new variation to then remove and take screenshots so sorry about that.
NOTE: If the product or variation is part of an order, then it can not be deleted.
> Adding deleting products frontend
